--- #  FULL INCLUDE TASKS EXAMPLE
- hosts: web-hosts
  user: user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify the telnet package is installed
      raw: yum list installed | grep telnet > /home/user/pkgs.log
