--- # My First YAML Playbook for Ansible note: sudo is depreciated, use become
- hosts: all
  user: user
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Remove httpd, telnet, lynx
      raw: yum remove httpd telnet lynx -y
      when: "ansible_os_family == 'RedHat'"
      ignore_errors: yes
    - name: Remove apache2, telnet, lynx
      raw: apt-get remove apache2 telnet lynx -y
      when: "ansible_os_family == 'Debian'"
      ignore_errors: yes
