--- # RUN ONCE PLAYBOOK EXAMPLE
- hosts: all
  user: user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /home/user/uptime.log
    - name: List the /var directory and log it
      raw: ls -al /var >> /home/user/dir.list
      run_once: true
