--- # START AT PLAYBOOK EXAMPLE
- hosts: web-hosts
  user: user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Telnet
    yum: pkg=telnet state=latest
  - name: Install Lynx
    yum: pkg=lynx state=latest
  - name: List Home
    command: ls -al /home/user
    register: result
  - debug: var=result

